function plotRslts(time_AltGDMin, SDVals_AltGDMin, ...
                   time_UnPerm, SDVals_UnPerm, ...
                   time_AltMinExct,SDVals_AltMinExct,...
                   time_AltMin, SDVals_AltMin, ...
                   n,q,r,m,numBlocks,MC,same,T_LS,eta_c)

    SDVals_AltGDMin = sum(SDVals_AltGDMin,1)/MC;
    SDVals_UnPerm = sum(SDVals_UnPerm,1)/MC;
    SDVals_AltMinExct = sum(SDVals_AltMinExct,1)/MC;   
    SDVals_AltMin = sum(SDVals_AltMin,1)/MC;
    %---
    time_UnPerm  = sum(time_UnPerm,1)/MC;
    time_AltGDMin = sum(time_AltGDMin,1)/MC;
    time_AltMinExct = sum(time_AltMinExct,1)/MC;
    time_AltMin = sum(time_AltMin,1)/MC;
    % SD vs iter figure
    figure;
    
    semilogy(SDVals_AltGDMin, ...
        'DisplayName', 'AltGDMin', 'LineWidth', 1.45, 'Marker', 'o', 'MarkerSize', 5);
    hold on;
    semilogy(SDVals_UnPerm, ...
        'DisplayName', 'Unpermuted', 'LineWidth', 1.45, 'Marker', 'x', 'MarkerSize', 5);
    semilogy(SDVals_AltMinExct, ...
        'DisplayName', 'AltMin (Exact)', 'LineWidth', 1.45, 'Marker', 'square', 'MarkerSize', 5);
    semilogy(SDVals_AltMin,...
         'DisplayName', 'AltMin (GD)', 'LineWidth', 1.45, 'Marker', 'x', 'MarkerSize', 5)
    grid on
    
    
    title("n = " + n + ", q = " + q +...
          ", r = " + r + ", m = " + m + ", num Blocks = " + numBlocks +  ", MC = " + MC + ", same = " + same, ...
           'Interpreter', 'Latex', 'FontSize',11)
    
    legend('Interpreter', 'Latex', 'Fontsize', 9);
    ylabel("$SD(U^{(t)},U^*)$","FontSize",14,'Interpreter','Latex')
    xlabel('Iterations (t)', 'FontSize',14, 'Interpreter','Latex')
    stringTitle = ['Iter_MC_', num2str(MC), ...
                   '_n_', num2str(n), '_q_', num2str(q), ...
                   '_r_', num2str(r), '_m_', num2str(m), ...
                   '_numBlocks_',num2str(numBlocks), '_same_',num2str(same), '_T_LS_', num2str(T_LS)];
    
    savefig([stringTitle, '.fig']);
    figure
    
    semilogy(time_AltGDMin, SDVals_AltGDMin, ...
        'DisplayName', ' AltGDMin', 'LineWidth', 1.45, 'Marker', 'o', 'MarkerSize', 5);
    hold on;
    %semilogy(SDVals_Perm, ...
    %    'DisplayName', 'SDVals (Naive)', 'LineWidth', 1.45, 'Marker', 'square', 'MarkerSize', 7);
    %
    semilogy(time_UnPerm, SDVals_UnPerm, ...
        'DisplayName', 'Unpermuted', 'LineWidth', 1.45, 'Marker', 'x', 'MarkerSize', 5);
    semilogy(time_AltMinExct, SDVals_AltMinExct, ...
        'DisplayName', 'AltMin (Exact)', 'LineWidth', 1.45, 'Marker', 'x', 'MarkerSize', 5);    
    semilogy(time_AltMin, SDVals_AltMin,...
         'DisplayName', 'AltMin (GD)', 'LineWidth', 1.45, 'Marker', 'x', 'MarkerSize', 5)
    grid on    
    title("n = " + n + ", q = " + q +...
          ", r = " + r + ", m = " + m + ", num Blocks = " + numBlocks +  ", MC = " + MC + ", same = " + same, ...
           'Interpreter', 'Latex', 'FontSize',11)
    
    legend('Interpreter', 'Latex', 'Fontsize', 9);
    ylabel("$SD(U^{(t)},U^*)$","FontSize",14,'Interpreter','Latex')
    xlabel('t (Seconds)', 'FontSize',14, 'Interpreter','Latex')
    stringTitle = ['Time_MC_', num2str(MC), ...
                   '_n_', num2str(n), '_q_', num2str(q), '_r_', num2str(r), ... 
                   '_m_', num2str(m), '_numBlocks_',num2str(numBlocks), ...
                   '_same_',num2str(same),'_T_LS_', num2str(T_LS), '_eta_c_',num2str(eta_c)];
    
    savefig([stringTitle, '.fig']);

end